name: dict
description: A more advanced implementation of Dart's native Map.
version: 1.0.0
author: Gil Mendes <gilmendes@designture.net>
homepage: https://github.com/Designture/dict
documentation:

environment:
  sdk: '>=1.12.0 <2.0.0'

dependencies:
  option: '>=1.1.0 <2.0.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
